export interface DrinkMarkedIngredients {
  strIngredient1: boolean,
  strIngredient2: boolean,
  strIngredient3: boolean,
  strIngredient4: boolean,
  strIngredient5: boolean,
  strIngredient6: boolean,
  strIngredient7: boolean,
  strIngredient8: boolean,
  strIngredient9: boolean,
  strIngredient10: boolean,
  strIngredient11: boolean,
  strIngredient12: boolean,
  strIngredient13: boolean,
  strIngredient14: boolean,
  strIngredient15: boolean,
}

export interface MealMarkedIngredients {
  strIngredient1: boolean,
  strIngredient2: boolean,
  strIngredient3: boolean,
  strIngredient4: boolean,
  strIngredient5: boolean,
  strIngredient6: boolean,
  strIngredient7: boolean,
  strIngredient8: boolean,
  strIngredient9: boolean,
  strIngredient10: boolean,
  strIngredient11: boolean,
  strIngredient12: boolean,
  strIngredient13: boolean,
  strIngredient14: boolean,
  strIngredient15: boolean,
  strIngredient16: boolean,
  strIngredient17: boolean,
  strIngredient18: boolean,
  strIngredient19: boolean,
  strIngredient20: boolean,
}
