{
"meals": [
{
"idMeal": "1",
"strMeal": "Beef and Mustard Pie",
"strDrinkAlternate": null,
"strCategory": "Beef",
"strArea": "British",
"strInstructions": "Preheat the oven to 150C/300F/Gas 2.\r\nToss the beef and flour together in a bowl with some salt and black pepper.\r\nHeat a large casserole until hot, add half of the rapeseed oil and enough of the beef to just cover the bottom of the casserole.\r\nFry until browned on each side, then remove and set aside. Repeat with the remaining oil and beef.\r\nReturn the beef to the pan, add the wine and cook until the volume of liquid has reduced by half, then add the stock, onion, carrots, thyme and mustard, and season well with salt and pepper.\r\nCover with a lid and place in the oven for two hours.\r\nRemove from the oven, check the seasoning and set aside to cool. Remove the thyme.\r\nWhen the beef is cool and you're ready to assemble the pie, preheat the oven to 200C/400F/Gas 6.\r\nTransfer the beef to a pie dish, brush the rim with the beaten egg yolks and lay the pastry over the top. Brush the top of the pastry with more beaten egg.\r\nTrim the pastry so there is just enough excess to crimp the edges, then place in the oven and bake for 30 minutes, or until the pastry is golden-brown and cooked through.\r\nFor the green beans, bring a saucepan of salted water to the boil, add the beans and cook for 4-5 minutes, or until just tender.\r\nDrain and toss with the butter, then season with black pepper.\r\nTo serve, place a large spoonful of pie onto each plate with some green beans alongside.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
"strTags": "Meat,Pie",
"strYoutube": "https://www.youtube.com/watch?v=nMyBC9staMU",
"strIngredient1": "Beef",
"strIngredient2": "Plain Flour",
"strIngredient3": "Rapeseed Oil",
"strIngredient4": "Red Wine",
"strIngredient5": "Beef Stock",
"strIngredient6": "Onion",
"strIngredient7": "Carrots",
"strIngredient8": "Thyme",
"strIngredient9": "Mustard",
"strIngredient10": "Egg Yolks",
"strIngredient11": "Puff Pastry",
"strIngredient12": "Green Beans",
"strIngredient13": "Butter",
"strIngredient14": "Salt",
"strIngredient15": "Pepper",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "1kg",
"strMeasure2": "2 tbs",
"strMeasure3": "2 tbs",
"strMeasure4": "200ml",
"strMeasure5": "400ml",
"strMeasure6": "1 finely sliced",
"strMeasure7": "2 chopped",
"strMeasure8": "3 sprigs",
"strMeasure9": "2 tbs",
"strMeasure10": "2 free-range",
"strMeasure11": "400g",
"strMeasure12": "300g",
"strMeasure13": "25g",
"strMeasure14": "pinch",
"strMeasure15": "pinch",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "https://www.bbc.co.uk/food/recipes/beef_and_mustard_pie_58002",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "2",
"strMeal": "Ayam Percik",
"strDrinkAlternate": null,
"strCategory": "Chicken",
"strArea": "Malaysian",
"strInstructions": "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
"strMealThumb": "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
"strTags": null,
"strYoutube": "https://www.youtube.com/watch?v=9ytR28QK6I8",
"strIngredient1": "Chicken Thighs",
"strIngredient2": "Challots",
"strIngredient3": "Ginger",
"strIngredient4": "Garlic Clove",
"strIngredient5": "Cayenne Pepper",
"strIngredient6": "Turmeric",
"strIngredient7": "Cumin",
"strIngredient8": "Coriander",
"strIngredient9": "Fennel",
"strIngredient10": "Tamarind Paste",
"strIngredient11": "Coconut Milk",
"strIngredient12": "Sugar",
"strIngredient13": "Water",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "6",
"strMeasure2": "16",
"strMeasure3": "1 1/2 ",
"strMeasure4": "6",
"strMeasure5": "8",
"strMeasure6": "2 tbs",
"strMeasure7": "1 1/2 ",
"strMeasure8": "1 1/2 ",
"strMeasure9": "1 1/2 ",
"strMeasure10": "2 tbs",
"strMeasure11": "1 can ",
"strMeasure12": "1 tsp ",
"strMeasure13": "1 cup ",
"strMeasure14": " ",
"strMeasure15": " ",
"strMeasure16": " ",
"strMeasure17": " ",
"strMeasure18": " ",
"strMeasure19": " ",
"strMeasure20": " ",
"strSource": "http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "3",
"strMeal": "Apam balik",
"strDrinkAlternate": null,
"strCategory": "Dessert",
"strArea": "Malaysian",
"strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
"strTags": null,
"strYoutube": "https://www.youtube.com/watch?v=6R8ffRRJcrg",
"strIngredient1": "Milk",
"strIngredient2": "Oil",
"strIngredient3": "Eggs",
"strIngredient4": "Flour",
"strIngredient5": "Baking Powder",
"strIngredient6": "Salt",
"strIngredient7": "Unsalted Butter",
"strIngredient8": "Sugar",
"strIngredient9": "Peanut Butter",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "200ml",
"strMeasure2": "60ml",
"strMeasure3": "2",
"strMeasure4": "1600g",
"strMeasure5": "3 tsp",
"strMeasure6": "1/2 tsp",
"strMeasure7": "25g",
"strMeasure8": "45g",
"strMeasure9": "3 tbs",
"strMeasure10": " ",
"strMeasure11": " ",
"strMeasure12": " ",
"strMeasure13": " ",
"strMeasure14": " ",
"strMeasure15": " ",
"strMeasure16": " ",
"strMeasure17": " ",
"strMeasure18": " ",
"strMeasure19": " ",
"strMeasure20": " ",
"strSource": "https://www.nyonyacooking.com/recipes/apam-balik~SJ5WuvsDf9WQ",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "4",
"strMeal": "Kapsalon",
"strDrinkAlternate": null,
"strCategory": "Lamb",
"strArea": "Dutch",
"strInstructions": "Cut the meat into strips. Heat oil in a pan and fry the strips for 6 minutes until it's ready.\r\nBake the fries until golden brown in a deep fryrer. When ready transfer to a backing dish. Make sure the fries are spread over the whole dish.\r\nCover the fries with a new layer of meat and spread evenly.\r\nAdd a layer of cheese over the meat. You can also use grated cheese. When done put in the oven for a few minutes until the cheese is melted.\r\nChop the lettuce, tomato and cucumber in small pieces and mix together. for a basic salad. As extra you can add olives jalapenos and a red union.\r\nDived the salad over the dish and Serve with garlicsauce and hot sauce",
"strMealThumb": "https://www.themealdb.com/images/media/meals/sxysrt1468240488.jpg",
"strTags": "Snack",
"strYoutube": "https://www.youtube.com/watch?v=UIcuiU1kV8I",
"strIngredient1": "Fries",
"strIngredient2": "Doner Meat",
"strIngredient3": "Garlic sauce",
"strIngredient4": "Hotsauce",
"strIngredient5": "Lettuce",
"strIngredient6": "Tomato",
"strIngredient7": "Cucumber",
"strIngredient8": "Gouda cheese",
"strIngredient9": "",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": null,
"strIngredient17": null,
"strIngredient18": null,
"strIngredient19": null,
"strIngredient20": null,
"strMeasure1": "250 Grams",
"strMeasure2": "500 Grams",
"strMeasure3": "Topping",
"strMeasure4": "Topping",
"strMeasure5": "1 Bulb",
"strMeasure6": "1",
"strMeasure7": "3rd",
"strMeasure8": "100 Grams",
"strMeasure9": "",
"strMeasure10": "",
"strMeasure11": "",
"strMeasure12": "",
"strMeasure13": "",
"strMeasure14": "",
"strMeasure15": "",
"strMeasure16": null,
"strMeasure17": null,
"strMeasure18": null,
"strMeasure19": null,
"strMeasure20": null,
"strSource": null,
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "5",
"strMeal": "Bean & Sausage Hotpot",
"strDrinkAlternate": null,
"strCategory": "Miscellaneous",
"strArea": "British",
"strInstructions": "In a large casserole, fry the sausages until brown all over – about 10 mins.\r\n\r\nAdd the tomato sauce, stirring well, then stir in the beans, treacle or sugar and mustard. Bring to the simmer, cover and cook for 30 mins. Great served with crusty bread or rice.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/vxuyrx1511302687.jpg",
"strTags": null,
"strYoutube": "https://www.youtube.com/watch?v=B0YX0yPX4Wo",
"strIngredient1": "Sausages",
"strIngredient2": "Tomato Sauce",
"strIngredient3": "Butter Beans",
"strIngredient4": "Black Treacle",
"strIngredient5": "English Mustard",
"strIngredient6": "",
"strIngredient7": "",
"strIngredient8": "",
"strIngredient9": "",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "8 large",
"strMeasure2": "1 Jar",
"strMeasure3": "1200g",
"strMeasure4": "1 tbls",
"strMeasure5": "1 tsp ",
"strMeasure6": "",
"strMeasure7": "",
"strMeasure8": "",
"strMeasure9": "",
"strMeasure10": "",
"strMeasure11": "",
"strMeasure12": "",
"strMeasure13": "",
"strMeasure14": "",
"strMeasure15": "",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "https://www.bbcgoodfood.com/recipes/339607/bean-and-sausage-hotpot",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "6",
"strMeal": "Chilli prawn linguine",
"strDrinkAlternate": null,
"strCategory": "Pasta",
"strArea": "Italian",
"strInstructions": "Mix the dressing ingredients in a small bowl and season with salt and pepper. Set aside.\r\n\r\nCook the pasta according to the packet instructions. Add the sugar snap peas for the last minute or so of cooking time.\r\n\r\nMeanwhile, heat the oil in a wok or large frying pan, toss in the garlic and chilli and cook over a fairly gentle heat for about 30 seconds without letting the garlic brown. Tip in the prawns and cook over a high heat, stirring frequently, for about 3 minutes until they turn pink.\r\n\r\nAdd the tomatoes and cook, stirring occasionally, for 3 minutes until they just start to soften. Drain the pasta and sugar snaps well, then toss into the prawn mixture. Tear in the basil leaves, stir, and season with salt and pepper.\r\n\r\nServe with salad leaves drizzled with the lime dressing, and warm crusty bread.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
"strTags": null,
"strYoutube": "https://www.youtube.com/watch?v=SC17Mc70Db0",
"strIngredient1": "Linguine Pasta",
"strIngredient2": "Sugar Snap Peas",
"strIngredient3": "Olive Oil",
"strIngredient4": "Garlic Clove",
"strIngredient5": "Red Chilli",
"strIngredient6": "King Prawns",
"strIngredient7": "Cherry Tomatoes",
"strIngredient8": "Basil Leaves",
"strIngredient9": "Lettuce",
"strIngredient10": "Bread",
"strIngredient11": "Fromage Frais",
"strIngredient12": "Lime",
"strIngredient13": "Caster Sugar",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "280g",
"strMeasure2": "200g",
"strMeasure3": "2 tblsp ",
"strMeasure4": "2 cloves chopped",
"strMeasure5": "1 large",
"strMeasure6": "24 Skinned",
"strMeasure7": "12",
"strMeasure8": "Handful",
"strMeasure9": "Leaves",
"strMeasure10": "to serve",
"strMeasure11": "2 tbsp",
"strMeasure12": "Grated Zest of 2",
"strMeasure13": "2 tsp",
"strMeasure14": "",
"strMeasure15": "",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "https://www.bbcgoodfood.com/recipes/1269/chilli-prawn-linguine",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "7",
"strMeal": " Bubble & Squeak",
"strDrinkAlternate": null,
"strCategory": "Pork",
"strArea": "British",
"strInstructions": "Melt the fat in a non-stick pan, allow it to get nice and hot, then add the bacon. As it begins to brown, add the onion and garlic. Next, add the sliced sprouts or cabbage and let it colour slightly. All this will take 5-6 mins.\r\nNext, add the potato. Work everything together in the pan and push it down so that the mixture covers the base of the pan – allow the mixture to catch slightly on the base of the pan before turning it over and doing the same again. It’s the bits of potato that catch in the pan that define the term ‘bubble and squeak’, so be brave and let the mixture colour. Cut into wedges and serve.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/xusqvw1511638311.jpg",
"strTags": "SideDish,Speciality",
"strYoutube": "https://www.youtube.com/watch?v=etbJ9ssgsWY",
"strIngredient1": "Butter",
"strIngredient2": "Bacon",
"strIngredient3": "Onion",
"strIngredient4": "Garlic Clove",
"strIngredient5": "Brussels Sprouts",
"strIngredient6": "Potatoes",
"strIngredient7": "",
"strIngredient8": "",
"strIngredient9": "",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "1 tbs",
"strMeasure2": "4",
"strMeasure3": "1 finely sliced",
"strMeasure4": "1 chopped",
"strMeasure5": "20",
"strMeasure6": "400g",
"strMeasure7": "",
"strMeasure8": "",
"strMeasure9": "",
"strMeasure10": "",
"strMeasure11": "",
"strMeasure12": "",
"strMeasure13": "",
"strMeasure14": "",
"strMeasure15": "",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "https://www.bbcgoodfood.com/recipes/164622/bubble-and-squeak",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "8",
"strMeal": "Baked salmon with fennel & tomatoes",
"strDrinkAlternate": null,
"strCategory": "Seafood",
"strArea": "British",
"strInstructions": "Heat oven to 180C/fan 160C/gas 4. Trim the fronds from the fennel and set aside. Cut the fennel bulbs in half, then cut each half into 3 wedges. Cook in boiling salted water for 10 mins, then drain well. Chop the fennel fronds roughly, then mix with the parsley and lemon zest.\r\n\r\nSpread the drained fennel over a shallow ovenproof dish, then add the tomatoes. Drizzle with olive oil, then bake for 10 mins. Nestle the salmon among the veg, sprinkle with lemon juice, then bake 15 mins more until the fish is just cooked. Scatter over the parsley and serve.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/1548772327.jpg",
"strTags": "Paleo,Keto,HighFat,Baking,LowCarbs",
"strYoutube": "https://www.youtube.com/watch?v=xvPR2Tfw5k0",
"strIngredient1": "Fennel",
"strIngredient2": "Parsley",
"strIngredient3": "Lemon",
"strIngredient4": "Cherry Tomatoes",
"strIngredient5": "Olive Oil",
"strIngredient6": "Salmon",
"strIngredient7": "Black Olives",
"strIngredient8": "",
"strIngredient9": "",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "2 medium",
"strMeasure2": "2 tbs chopped",
"strMeasure3": "Juice of 1",
"strMeasure4": "175g",
"strMeasure5": "1 tbs",
"strMeasure6": "350g",
"strMeasure7": "to serve",
"strMeasure8": "",
"strMeasure9": "",
"strMeasure10": "",
"strMeasure11": "",
"strMeasure12": "",
"strMeasure13": "",
"strMeasure14": "",
"strMeasure15": "",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "https://www.bbcgoodfood.com/recipes/7745/baked-salmon-with-fennel-and-tomatoes",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "9",
"strMeal": "Blini Pancakes",
"strDrinkAlternate": null,
"strCategory": "Side",
"strArea": "Russian",
"strInstructions": "In a large bowl, whisk together 1/2 cup buckwheat flour, 2/3 cup all-purpose flour, 1/2 teaspoon salt, and 1 teaspoon yeast.\r\n\r\nMake a well in the center and pour in 1 cup warm milk, whisking until the batter is smooth.\r\n\r\nCover the bowl and let the batter rise until doubled, about 1 hour.\r\n\r\nEnrich and Rest the Batter\r\nStir 2 tablespoons melted butter and 1 egg yolk into the batter.\r\n\r\nIn a separate bowl, whisk 1 egg white until stiff, but not dry.\r\n\r\nFold the whisked egg white into the batter.\r\n\r\nCover the bowl and let the batter stand 20 minutes.\r\n\r\nPan-Fry the Blini\r\nHeat butter in a large nonstick skillet over medium heat.\r\n\r\nDrop quarter-sized dollops of batter into the pan, being careful not to overcrowd the pan. Cook for about 1 minute or until bubbles form.\r\n\r\nTurn and cook for about 30 additional seconds.\r\n\r\nRemove the finished blini onto a plate and cover them with a clean kitchen towel to keep warm. Add more butter to the pan and repeat the frying process with the remaining batter.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/0206h11699013358.jpg",
"strTags": "pancake",
"strYoutube": "https://www.youtube.com/watch?v=GsB8ZI5vREA",
"strIngredient1": "Buckwheat",
"strIngredient2": "Flour",
"strIngredient3": "Salt",
"strIngredient4": "Yeast",
"strIngredient5": "Milk",
"strIngredient6": "Butter",
"strIngredient7": "Egg",
"strIngredient8": "",
"strIngredient9": "",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "1/2 cup ",
"strMeasure2": "2/3 Cup",
"strMeasure3": "1/2 tsp",
"strMeasure4": "1 tsp ",
"strMeasure5": "1 cup ",
"strMeasure6": "2 tbs",
"strMeasure7": "1 Seperated",
"strMeasure8": " ",
"strMeasure9": " ",
"strMeasure10": " ",
"strMeasure11": " ",
"strMeasure12": " ",
"strMeasure13": " ",
"strMeasure14": " ",
"strMeasure15": " ",
"strMeasure16": " ",
"strMeasure17": " ",
"strMeasure18": " ",
"strMeasure19": " ",
"strMeasure20": " ",
"strSource": "https://www.thespruceeats.com/russian-blini-recipe-buckwheat-pancakes-1136797",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "10",
"strMeal": "Broccoli & Stilton soup",
"strDrinkAlternate": null,
"strCategory": "Starter",
"strArea": "British",
"strInstructions": "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
"strTags": null,
"strYoutube": "https://www.youtube.com/watch?v=_HgVLpmNxTY",
"strIngredient1": "Rapeseed Oil",
"strIngredient2": "Onion",
"strIngredient3": "Celery",
"strIngredient4": "Leek",
"strIngredient5": "Potatoes",
"strIngredient6": "Butter",
"strIngredient7": "Vegetable Stock",
"strIngredient8": "Broccoli",
"strIngredient9": "Stilton Cheese",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "2 tblsp ",
"strMeasure2": "1 finely chopped ",
"strMeasure3": "1",
"strMeasure4": "1 sliced",
"strMeasure5": "1 medium",
"strMeasure6": "1 knob",
"strMeasure7": "1 litre hot",
"strMeasure8": "1 Head chopped",
"strMeasure9": "140g",
"strMeasure10": "",
"strMeasure11": "",
"strMeasure12": "",
"strMeasure13": "",
"strMeasure14": "",
"strMeasure15": "",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "11",
"strMeal": "Roast fennel and aubergine paella",
"strDrinkAlternate": null,
"strCategory": "Vegan",
"strArea": "Spanish",
"strInstructions": "1 Put the fennel, aubergine, pepper and courgette in a roasting tray. Add a glug of olive oil, season with salt and pepper and toss around to coat the veggies in the oil. Roast in the oven for 20 minutes, turning a couple of times until the veg are pretty much cooked through and turning golden.\r\n\r\n2 Meanwhile, heat a paella pan or large frying pan over a low– medium heat and add a glug of olive oil. Sauté the onion for 8–10 minutes until softened. Increase the heat to medium and stir in the rice, paprika and saffron. Cook for around 1 minute to start toasting the rice, then add the white wine. Reduce by about half before stirring in two-thirds of the stock. Reduce to a simmer and cook for 10 minutes without a lid, stirring a couple of times.\r\n\r\n3 Stir in the peas, add some seasoning, then gently mix in the roasted veg. Pour over the remaining stock, arrange the lemon wedges on top and cover with a lid or some aluminium foil. Cook for a further 10 minutes.\r\n\r\n4 To ensure you get the classic layer of toasted rice at the bottom of the pan, increase the heat to high until you hear a slight crackle. Remove from the heat and sit for 5 minutes before sprinkling over the parsley and serving.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/1520081754.jpg",
"strTags": "Vegan,Paella",
"strYoutube": "https://www.youtube.com/watch?v=H5SmjR-fxUs",
"strIngredient1": "Baby Aubergine",
"strIngredient2": "Fennel",
"strIngredient3": "Red Pepper",
"strIngredient4": "Courgettes",
"strIngredient5": "Onion",
"strIngredient6": "Paella Rice",
"strIngredient7": "Paprika",
"strIngredient8": "Saffron",
"strIngredient9": "White Wine",
"strIngredient10": "Vegetable Stock",
"strIngredient11": "Frozen Peas",
"strIngredient12": "Lemon",
"strIngredient13": "Parsley",
"strIngredient14": "Salt",
"strIngredient15": "Black Pepper",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "6 small",
"strMeasure2": "4 small",
"strMeasure3": "1 thinly sliced",
"strMeasure4": "1 medium",
"strMeasure5": "1 finely chopped ",
"strMeasure6": "300g",
"strMeasure7": "1 tsp ",
"strMeasure8": "pinch",
"strMeasure9": "200ml",
"strMeasure10": "700ml",
"strMeasure11": "100g ",
"strMeasure12": "1 chopped",
"strMeasure13": "Handful",
"strMeasure14": "pinch",
"strMeasure15": "pinch",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "https://www.homestylemag.co.uk/recipe/517/main-courses/roast-fennel-and-aubergine-paella",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "12",
"strMeal": "Baingan Bharta",
"strDrinkAlternate": null,
"strCategory": "Vegetarian",
"strArea": "Indian",
"strInstructions": "Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and\r\nkeep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won't get\r\nthe smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly\r\ncooked. You could also embed some garlic cloves in the baingan and then roast it.\r\n2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid\r\neasily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools\r\ndown.\r\n3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step.\r\nUse natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red.\r\n4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted\r\naubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke.\r\n5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the\r\ncharcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will\r\nbecome. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is\r\ncooked, just like the way we do for Dal Tadka.\r\n6. Peel the skin from the roasted and smoked eggplant.\r\n7. Chop the cooked eggplant finely or you can even mash it.\r\n8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic.\r\n9. Saute the onions till translucent. Don't brown them.\r\n10. Add chopped green chilies and saute for a minute.\r\n11. Add the chopped tomatoes and mix it well.\r\n12. Bhuno (saute) the tomatoes till the oil starts separating from the mixture.\r\n13. Now add the red chili powder. Stir and mix well.\r\n14. Add the chopped cooked baingan.\r\n15. Stir and mix the chopped baingan very well with the onion­tomato masala mixture.\r\n16. Season with salt. Stir and saute for some more 4 to 5 minutes more.\r\n17. Finally stir in the coriander leaves with the baingan bharta or garnish it with them. Serve Baingan Bharta with\r\nphulkas, rotis or chapatis. It goes well even with bread, toasted or grilled bread and plain rice or jeera rice.",
"strMealThumb": "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
"strTags": "Spicy,Bun,Calorific",
"strYoutube": "https://www.youtube.com/watch?v=-84Zz2EP4h4",
"strIngredient1": "Aubergine",
"strIngredient2": "Onion",
"strIngredient3": "Tomatoes",
"strIngredient4": "Garlic",
"strIngredient5": "Green Chili",
"strIngredient6": "Red Chili Powder",
"strIngredient7": "Oil",
"strIngredient8": "Coriander Leaves",
"strIngredient9": "salt",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "1 large",
"strMeasure2": "½ cup ",
"strMeasure3": "1 cup",
"strMeasure4": "6 cloves",
"strMeasure5": "1",
"strMeasure6": "¼ teaspoon",
"strMeasure7": "1.5 tablespoon",
"strMeasure8": "1 tablespoon chopped",
"strMeasure9": "as required",
"strMeasure10": "",
"strMeasure11": "",
"strMeasure12": "",
"strMeasure13": "",
"strMeasure14": "",
"strMeasure15": "",
"strMeasure16": "",
"strMeasure17": "",
"strMeasure18": "",
"strMeasure19": "",
"strMeasure20": "",
"strSource": "http://www.vegrecipesofindia.com/baingan-bharta-recipe-punjabi-baingan-bharta-recipe/",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "13",
"strMeal": "Bread omelette",
"strDrinkAlternate": null,
"strCategory": "Breakfast",
"strArea": "Indian",
"strInstructions": "Make and enjoy",
"strMealThumb": "https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg",
"strTags": null,
"strYoutube": "",
"strIngredient1": "Bread",
"strIngredient2": "Egg",
"strIngredient3": "Salt",
"strIngredient4": "",
"strIngredient5": "",
"strIngredient6": "",
"strIngredient7": "",
"strIngredient8": "",
"strIngredient9": "",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "2",
"strMeasure2": "2",
"strMeasure3": "0.5",
"strMeasure4": " ",
"strMeasure5": " ",
"strMeasure6": " ",
"strMeasure7": " ",
"strMeasure8": " ",
"strMeasure9": " ",
"strMeasure10": " ",
"strMeasure11": " ",
"strMeasure12": " ",
"strMeasure13": " ",
"strMeasure14": " ",
"strMeasure15": " ",
"strMeasure16": " ",
"strMeasure17": " ",
"strMeasure18": " ",
"strMeasure19": " ",
"strMeasure20": " ",
"strSource": "",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
},
{
"idMeal": "14",
"strMeal": "Mbuzi Choma (Roasted Goat)",
"strDrinkAlternate": null,
"strCategory": "Goat",
"strArea": "Kenyan",
"strInstructions": "1. Steps for the Meat: \r\n Roast meat over medium heat for 50 minutes and salt it as you turn it.\r\n\r\n2. Steps for Ugali:\r\nBring the water and salt to a boil in a heavy-bottomed saucepan. Stir in the cornmeal slowly, letting it fall through the fingers of your hand.\r\n\r\n3. Reduce heat to medium-low and continue stirring regularly, smashing any lumps with a spoon, until the mush pulls away from the sides of the pot and becomes very thick, about 10 minutes.\r\n\r\n4.Remove from heat and allow to cool.\r\n\r\n5. Place the ugali into a large serving bowl. Wet your hands with water, form a ball and serve.\r\n\r\n6. Steps for Kachumbari: Mix the tomatoes, onions, chili and coriander leaves in a bowl.\r\n\r\n7. Serve and enjoy!\r\n\r\n",
"strMealThumb": "https://www.themealdb.com/images/media/meals/cuio7s1555492979.jpg",
"strTags": "BBQ,Meat",
"strYoutube": "",
"strIngredient1": "Goat Meat",
"strIngredient2": "Corn Flour",
"strIngredient3": "Tomatoes",
"strIngredient4": "Salt",
"strIngredient5": "Onion",
"strIngredient6": "Green Chilli",
"strIngredient7": "Coriander Leaves",
"strIngredient8": "",
"strIngredient9": "",
"strIngredient10": "",
"strIngredient11": "",
"strIngredient12": "",
"strIngredient13": "",
"strIngredient14": "",
"strIngredient15": "",
"strIngredient16": "",
"strIngredient17": "",
"strIngredient18": "",
"strIngredient19": "",
"strIngredient20": "",
"strMeasure1": "1 kg",
"strMeasure2": "1 kg",
"strMeasure3": "2",
"strMeasure4": "Pinch",
"strMeasure5": "1",
"strMeasure6": "1",
"strMeasure7": "1  bunch",
"strMeasure8": " ",
"strMeasure9": " ",
"strMeasure10": " ",
"strMeasure11": " ",
"strMeasure12": " ",
"strMeasure13": " ",
"strMeasure14": " ",
"strMeasure15": " ",
"strMeasure16": " ",
"strMeasure17": " ",
"strMeasure18": " ",
"strMeasure19": " ",
"strMeasure20": " ",
"strSource": "",
"strImageSource": null,
"strCreativeCommonsConfirmed": null,
"dateModified": null
}
]
}